config/routes.rb
Evehelper::Application.routes.draw do
  root to: 'regions#index'

  resources :regions, only: :index

  match '/region/:region_name', to: 'regions#show', as: :region_show, via: 'get'
  match '/region/:region_name/edit', to: 'regions#edit', as: :region_edit, via: 'get'
  match '/region/:region_name/update', to: 'regions#update', as: :region_update, via: 'post'

end

app/models/linked_system.rb
class LinkedSystem < ActiveRecord::Base
  attr_accessible :solar_system, :link

  belongs_to :solar_system
  belongs_to :link, :class_name => "SolarSystem"



end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :solar_systems

  def update_solar_systems(solar_system_data)
    self.solar_systems.each {|solar_system| solar_system.set_x_and_y(solar_system_data[solar_system.name])}
  end

  def self.find_by_given_name(name)
    self.where("lower(name) = ?", name.downcase).first
  end
end

app/models/solar_system.rb
class SolarSystem < ActiveRecord::Base
  attr_accessible :name, :region, :eve_id, :station

  belongs_to :region
  has_many :updates
  has_many :linked_systems
  has_many :links, :through => :linked_systems, :class_name => "SolarSystem"
  has_many :stats, :order => "created_at DESC"

  #These methods are used as a shortcut to access their most recent stats
  def most_recent
    self.stats.first
  end

  def npc_kills
    most_recent.npc_kills
  end

  def ship_kills
    most_recent.ship_kills
  end

  def pod_kills
    most_recent.ship_kills
  end

  def jumps
    most_recent.jumps
  end

  def set_x_and_y(coordinate_values)
    self.x = coordinate_values[:x]
    self.y = coordinate_values[:y]
    self.save
  end
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  attr_accessible :jumps, :npc_kills, :pod_kills, :ship_kills

  belongs_to :solar_system

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
  end

  def show
    @region = Region.find_by_given_name(params[:region_name])
    @data = SolarSystem.where(region_id: @region.id).to_json(:methods => [:jumps, :npc_kills, :ship_kills, :pod_kills], :except => [:region_id, :created_at, :updated_at])
    @links = SolarSystem.where(region_id: @region.id).map{|system| system.linked_systems}.flatten.to_json
  end

  # Edit and Update methods/routes to be removed once database has all x/y values

  def edit
    @region = Region.find_by_given_name(params[:region_name])
    @data = SolarSystem.where(region_id: @region.id).to_json(:except => [:region_id, :created_at, :updated_at])
  end

  def update
    @region = Region.find_by_given_name(params[:region_name])
    @region.update_solar_systems(params[:solarSystemData])
    render :js => "/region/#{@region.name}"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def region_names
    ["Aridia", "Black Rise", "Branch", "Cache", "Catch", "Cloud Ring", "Cobalt Edge",
     "Curse", "Deklein", "Delve", "Derelik", "Detorid", "Devoid", "Domain", "Esoteria",
     "Essence", "Etherium Reach", "Everyshore", "Fade", "Feythabolis", "Fountain",
     "Geminate", "Genesis", "Great Wildlands", "Heimatar", "Immensea", "Impass", "Insmother",
     "Kador", "Khanid", "Kor-Azor", "Lonetrek", "Malpais", "Metropolis", "Molden Heath",
     "Oasa", "Omist", "Outer Passage", "Outer Ring", "Paragon Soul", "Period Basis",
     "Perrigen Falls", "Placid", "Providence", "Pure Blind", "Querious", "Scalding Pass",
     "Sinq Laison", "Solitude", "Stain", "Syndicate", "Tash-Murkon", "Tenal", "Tenerifis",
     "The Bleak Lands", "The Citadel", "The Forge", "The Kalevala Expanse", "The Spire",
     "Tribute", "Vale of the Silent", "Venal", "Verge Vendor", "Wicked Creek"]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evehelper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
</head>
<body>
<div id="header">
  <span id="logo">
    <h1><span>EVE</span>&nbsp;Target Finder</h1>
  </span>
</div>

<div id="body-wrapper">
<%= yield %>
</div>

</body>
</html>

app/views/regions/edit.html.erb
  <svg id="map" width="1200" height="800"></svg>
  <div id="systems">
    <form name="system-data" action="<%= region_update_path(@region.name) %>" method="post">
      <table>
      </table>
      <input type="submit" id="submit" value="Post X/Y Values">
    </form>
  </div>
  <div id="results">
  </div>
<script src="/tipsy.js"></script>
<script>
var dataset = <%= @data.to_s.html_safe %>;
var gatheredData = {}


var height = 800
var width = 1200
var radius = 10

var drag = d3.behavior.drag()
    .on("drag", dragMove)

function dragMove(d) {
  // console.log("System: " + d.name +" X:" + d3.event.x + " Y: " + d3.event.y)
  var newX = d3.mouse(this)[0]
  var newY = Math.round(d3.mouse(this)[1])
  updateForm(d.name, newX, newY)
  d3.select(this)
    .attr("cx", d.x = Math.max(radius, Math.min(width - radius, newX)))
    .attr("cy", d.y = Math.max(radius, Math.min(height - radius, newY)));
}

function systemForm() {
  for(ind in dataset) {
    var systemName = dataset[ind].name
    var systemFormHTML = "<tr><td><span>"+ systemName +":</span></td><td><input type=\"text\" name="+ systemName +" id="+ systemName +"></td></tr>"
    $('table').append(systemFormHTML)
  }
}

function updateForm(selector, x, y) {
  $("input#" + selector).attr("value", x + "," + y)
}

function compileAndPostResults() {
  resetData();
  $("input[type=text]").each(function() {
    var solarSystemName = $(this).attr("id")
    var x = $(this).attr("value").split(',')[0]
    var y = $(this).attr("value").split(',')[1]
    gatheredData[solarSystemName] = {}
    gatheredData[solarSystemName].x = x
    gatheredData[solarSystemName].y = y
  })
  postData();
}

function postData() {
  var url = $("form").attr('action')
  $.ajax({
    url: url,
    type: 'post',
    dataType: 'JSON',
    contentType: 'application/json',
    processData: false,
    data: JSON.stringify({solarSystemData: gatheredData}),
    complete: function(response) {
      window.location = response.responseText
    }
  })
}

function resetData() {
  gatheredData = {}
}

$(document).ready(function() {
  systemForm()

  var map = d3.select("#map")
              .append("svg")
              .attr("height", height)
              .attr("width", width)

  var systems = map.selectAll("circle")
                   .data(dataset)
                   .enter()
                   .append("circle")

  systems.attr("cx", function(data, index) {
            return (index * 10) + 5;
          })
         .attr("cy", function(data, index) {
            return (index * 10) + 5;
          })
         .attr("r", radius)
         .attr('fill', 'orange')
         .attr('stroke', 'yellow')
         .attr('stroke-width', '2px')
         .attr('class', 'solar-system')
         .call(drag)

  $('.solar-system').tipsy({
        gravity: 'sw',
        html: true,
        // trigger: 'manual',
        title: function() {
          var d = this.__data__;
          return 'System: ' + d.name;
        }
      });


  $("#submit").on("click", function(event) {
    event.preventDefault();
    compileAndPostResults();
  })
})

</script>

app/views/regions/index.html.erb
<% region_names.each do |region_name| %>
  <div class="regions-map"><%= link_to region_name, region_show_path(region_name) %></div>
<% end %>

app/views/regions/show.html.erb
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="/tipsy.js"></script>
<h3><%= @region.name %></h3>
<svg id="map" width="1200" height="800"></svg>
</div>
<script>
  // below is the solar system data in JSON format for use with the D3 library for display.
  var dataset = <%= @data.to_s.html_safe %>;
  var links = <%= @links.to_s.html_safe %>[0];
  $(document).ready(function() {
    var height = 800
    var width = 1200
    var radius = 10

    var map = d3.select("#map")
    .append("svg")
    .attr("height", height)
    .attr("width", width)

    var systems = map.selectAll("circle")
    .data(dataset)
    .enter()
    .append("circle")

    systems.attr("cx", function(data, index) {
      return data.x;
    })
    .attr("cy", function(data, index) {
      return data.y;
    })
    .attr("r", radius)
    .attr('fill', 'orange')
    .attr('stroke', 'yellow')
    .attr('stroke-width', '2px')
    .attr('class', 'solar-system')

    $('.solar-system').tipsy({
      gravity: 'sw',
      html: true,
        // trigger: 'manual',
        title: function() {
          var d = this.__data__;
          return 'System: ' + d.name;
        }
      });
    })
  </script>

app/views/welcome/landing.html.erb
<p><%= link_to "Regions", regions_path %></p>